version: '2.0'

services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    tty: true
    restart: always
    volumes:
      - $HOME/.docker-compose/mysql:/var/lib/mysql
    &env environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4306:3306"

  centos:
    image: centos:latest
    container_name: centos
    hostname: hello
    tty: true
    *env:
      - TEST=123
    restart: always
    depends_on: ['db']
