version: '2.0'

services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    tty: true
    volumes:
      - $HOME/.docker-compose/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
